# -*- coding: utf-8 -*-
"""ingrezza_fda_adverse_events.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgJ4iJeEC55kUth5o_hjPQFZJUazol4D
"""

import requests

# Step 1 - Call the FDA API
response = requests.get(
    "https://api.fda.gov/drug/event.json",
    params={"search": "patient.drug.medicinalproduct:INGREZZA", "limit": 5}
)

# Step 2 - Handle errors
if response.status_code != 200:
    print(f"API call failed with status: {response.status_code}")
else:
    data = response.json()
    results = data["results"]

    # Step 3 - Transform and extract clean fields
    for event in results:
        print({
            "report_date": event.get("receiptdate"),
            "serious": event.get("serious"),
            "country": event.get("occurcountry"),
            "reaction": event.get("patient", {}).get("reaction", [{}])[0].get("reactionmeddrapt", "unknown")
        })

